package org.lucassus.jmine.dialogs;

import java.awt.Rectangle;

/**
 *
 * @author  lucassus
 */
public class JDialogAbout extends javax.swing.JDialog {
	
	/** Creates new form JDialogAbout */
	public JDialogAbout(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		Rectangle parentBounds = parent.getBounds();
		setLocation(parentBounds.x + 20, parentBounds.y + 20);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        toggleButtonOk = new javax.swing.JToggleButton();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        toggleButtonOk.setText("Ok");
        toggleButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(toggleButtonOk, gridBagConstraints);

        textArea.setBackground(new java.awt.Color(238, 238, 238));
        textArea.setEditable(false);
        textArea.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textArea.setText("Author:\tŁukasz Bandzarewicz\nEmail:\tlukasz.bandzarewicz@gmail.com\n\t(C) 2005 - 2010");
        getContentPane().add(textArea, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void toggleButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonOkActionPerformed
		setVisible(false);
		dispose();
	}//GEN-LAST:event_toggleButtonOkActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    private javax.swing.JToggleButton toggleButtonOk;
    // End of variables declaration//GEN-END:variables
	
}
