/*
 * JDialogPreferences.java
 *
 * Created on 29 sierpie� 2005, 19:13
 */
package org.lucassus.jmine.dialogs;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.lucassus.jmine.JMineFrame;
import org.lucassus.jmine.field.GameTypeException;
import org.lucassus.jmine.field.MineField;
import java.awt.Rectangle;
import javax.swing.JSlider;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.lucassus.jmine.field.GameType;

/**
 *
 * @author  lucassus
 */
public class JDialogPreferences extends javax.swing.JDialog {

    private class SliderListener implements ChangeListener {

        JTextField textField;

        SliderListener(JTextField textField) {
            this.textField = textField;
        }

        @Override
        public void stateChanged(ChangeEvent evt) {
            JSlider slider = (JSlider) evt.getSource();
            textField.setText(Integer.toString(slider.getValue()));

            int fieldWidth = jSliderMineFieldWidth.getValue();
            int fieldHeight = jSliderMineFieldHeight.getValue();
            int maxMines = (int) Math.ceil((fieldHeight * fieldWidth) / 2);
            jSliderNumberOfMines.setMaximum(maxMines);
        }
    }
    private MineField mineField;

    /**
     * Creates new form JDialogPreferences
     * @param parent
     * @param modal
     */
    public JDialogPreferences(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Rectangle parentBounds = parent.getBounds();
        setLocation(parentBounds.x + 20, parentBounds.y + 20);

        mineField = ((JMineFrame) parent).getMineField();

        initializeSliders(mineField.getGameType());
        jSliderMineFieldWidth.addChangeListener(new SliderListener(jTextFieldMineFieldWidth));
        jSliderMineFieldHeight.addChangeListener(new SliderListener(jTextFieldMineFieldHeight));
        jSliderNumberOfMines.addChangeListener(new SliderListener(jTextFieldNumberOfMines));

        if (mineField.getGameType() == GameType.NOVICE) {
            jRadioButtonNoviceGame.setSelected(true);
            disableUserSettings();
        } else if (mineField.getGameType() == GameType.INTERMEDIATE) {
            jRadioButtonIntermediateGame.setSelected(true);
            disableUserSettings();
        } else if (mineField.getGameType() == GameType.EXPERT) {
            jRadioButtonExpertGame.setSelected(true);
            disableUserSettings();
        } else {
            jRadioButtonUserGame.setSelected(true);
            enableUserSettings();
        }
    }

    private void initializeSliders(GameType gameType) {
        jSliderMineFieldWidth.setValue(gameType.getMineFieldWidth());
        jSliderMineFieldHeight.setValue(gameType.getMineFieldHeight());
        jSliderNumberOfMines.setValue(gameType.getNumberOfMines());
    }

    private void enableUserSettings() {
        setUserSettingsEnabled(true);
    }

    private void disableUserSettings() {
        setUserSettingsEnabled(false);
    }

    private void setUserSettingsEnabled(boolean enabled) {
        jSliderMineFieldWidth.setEnabled(enabled);
        jSliderMineFieldHeight.setEnabled(enabled);
        jSliderNumberOfMines.setEnabled(enabled);
        jLabel1.setEnabled(enabled);
        jLabel2.setEnabled(enabled);
        jLabel3.setEnabled(enabled);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroupGameDifficult = new javax.swing.ButtonGroup();
        jPanelDifficult = new javax.swing.JPanel();
        jRadioButtonNoviceGame = new javax.swing.JRadioButton();
        jRadioButtonIntermediateGame = new javax.swing.JRadioButton();
        jRadioButtonExpertGame = new javax.swing.JRadioButton();
        jRadioButtonUserGame = new javax.swing.JRadioButton();
        jPanelUserSettings = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSliderMineFieldWidth = new javax.swing.JSlider();
        jSliderMineFieldHeight = new javax.swing.JSlider();
        jSliderNumberOfMines = new javax.swing.JSlider();
        jTextFieldMineFieldWidth = new javax.swing.JTextField();
        jTextFieldMineFieldHeight = new javax.swing.JTextField();
        jTextFieldNumberOfMines = new javax.swing.JTextField();
        jPanelButtons = new javax.swing.JPanel();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelDifficult.setBorder(javax.swing.BorderFactory.createTitledBorder("Game difficult"));
        jPanelDifficult.setLayout(new java.awt.GridBagLayout());

        buttonGroupGameDifficult.add(jRadioButtonNoviceGame);
        jRadioButtonNoviceGame.setText("Novice");
        jRadioButtonNoviceGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoviceGameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelDifficult.add(jRadioButtonNoviceGame, gridBagConstraints);

        buttonGroupGameDifficult.add(jRadioButtonIntermediateGame);
        jRadioButtonIntermediateGame.setText("Intermediate");
        jRadioButtonIntermediateGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonIntermediateGameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelDifficult.add(jRadioButtonIntermediateGame, gridBagConstraints);

        buttonGroupGameDifficult.add(jRadioButtonExpertGame);
        jRadioButtonExpertGame.setText("Expert");
        jRadioButtonExpertGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonExpertGameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelDifficult.add(jRadioButtonExpertGame, gridBagConstraints);

        buttonGroupGameDifficult.add(jRadioButtonUserGame);
        jRadioButtonUserGame.setText("User");
        jRadioButtonUserGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUserGameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanelDifficult.add(jRadioButtonUserGame, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(jPanelDifficult, gridBagConstraints);

        jPanelUserSettings.setBorder(javax.swing.BorderFactory.createTitledBorder("User"));
        jPanelUserSettings.setEnabled(false);
        jPanelUserSettings.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Mine field width:");
        jLabel1.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jPanelUserSettings.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Mine field height:");
        jLabel2.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 2);
        jPanelUserSettings.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Number of mines:");
        jLabel3.setEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 2);
        jPanelUserSettings.add(jLabel3, gridBagConstraints);

        jSliderMineFieldWidth.setMaximum(64);
        jSliderMineFieldWidth.setMinimum(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jPanelUserSettings.add(jSliderMineFieldWidth, gridBagConstraints);

        jSliderMineFieldHeight.setMaximum(64);
        jSliderMineFieldHeight.setMinimum(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jPanelUserSettings.add(jSliderMineFieldHeight, gridBagConstraints);

        jSliderNumberOfMines.setMinimum(1);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jPanelUserSettings.add(jSliderNumberOfMines, gridBagConstraints);

        jTextFieldMineFieldWidth.setEditable(false);
        jTextFieldMineFieldWidth.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMineFieldWidth.setText("0");
        jTextFieldMineFieldWidth.setMinimumSize(new java.awt.Dimension(20, 19));
        jTextFieldMineFieldWidth.setPreferredSize(new java.awt.Dimension(40, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanelUserSettings.add(jTextFieldMineFieldWidth, gridBagConstraints);

        jTextFieldMineFieldHeight.setEditable(false);
        jTextFieldMineFieldHeight.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldMineFieldHeight.setText("0");
        jTextFieldMineFieldHeight.setMinimumSize(new java.awt.Dimension(20, 19));
        jTextFieldMineFieldHeight.setPreferredSize(new java.awt.Dimension(40, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanelUserSettings.add(jTextFieldMineFieldHeight, gridBagConstraints);

        jTextFieldNumberOfMines.setEditable(false);
        jTextFieldNumberOfMines.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldNumberOfMines.setText("0");
        jTextFieldNumberOfMines.setMinimumSize(new java.awt.Dimension(20, 19));
        jTextFieldNumberOfMines.setPreferredSize(new java.awt.Dimension(40, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanelUserSettings.add(jTextFieldNumberOfMines, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        getContentPane().add(jPanelUserSettings, gridBagConstraints);

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 2);
        jPanelButtons.add(jButtonOk, gridBagConstraints);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelButtons.add(jButtonCancel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanelButtons, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jRadioButtonUserGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUserGameActionPerformed
            initializeSliders(GameType.USER);
            setUserSettingsEnabled(true);
	}//GEN-LAST:event_jRadioButtonUserGameActionPerformed

	private void jRadioButtonExpertGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonExpertGameActionPerformed
            initializeSliders(GameType.EXPERT);
            setUserSettingsEnabled(false);
	}//GEN-LAST:event_jRadioButtonExpertGameActionPerformed

	private void jRadioButtonIntermediateGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonIntermediateGameActionPerformed
            initializeSliders(GameType.INTERMEDIATE);
            setUserSettingsEnabled(false);
	}//GEN-LAST:event_jRadioButtonIntermediateGameActionPerformed

	private void jRadioButtonNoviceGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoviceGameActionPerformed
            initializeSliders(GameType.NOVICE);
            setUserSettingsEnabled(false);
	}//GEN-LAST:event_jRadioButtonNoviceGameActionPerformed

	private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
            if (jRadioButtonNoviceGame.isSelected()) {
                mineField.setGameType(GameType.NOVICE);
            } else if (jRadioButtonIntermediateGame.isSelected()) {
                mineField.setGameType(GameType.INTERMEDIATE);
            } else if (jRadioButtonExpertGame.isSelected()) {
                mineField.setGameType(GameType.EXPERT);
            } else {
                int height = jSliderMineFieldHeight.getValue();
                int width = jSliderMineFieldWidth.getValue();
                int mines = jSliderNumberOfMines.getValue();

                try {
                    GameType.USER.setMineFieldWidth(width);
                    GameType.USER.setMineFieldHeight(height);
                    GameType.USER.setNumberOfMines(mines);
                } catch (GameTypeException ex) {
                    Logger.getLogger(JDialogPreferences.class.getName()).log(Level.SEVERE, null, ex);
                }

                mineField.setGameType(GameType.USER);
            }

            setVisible(false);
            dispose();
	}//GEN-LAST:event_jButtonOkActionPerformed

	private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
            setVisible(false);
            dispose();
	}//GEN-LAST:event_jButtonCancelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGameDifficult;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelDifficult;
    private javax.swing.JPanel jPanelUserSettings;
    private javax.swing.JRadioButton jRadioButtonExpertGame;
    private javax.swing.JRadioButton jRadioButtonIntermediateGame;
    private javax.swing.JRadioButton jRadioButtonNoviceGame;
    private javax.swing.JRadioButton jRadioButtonUserGame;
    private javax.swing.JSlider jSliderMineFieldHeight;
    private javax.swing.JSlider jSliderMineFieldWidth;
    private javax.swing.JSlider jSliderNumberOfMines;
    private javax.swing.JTextField jTextFieldMineFieldHeight;
    private javax.swing.JTextField jTextFieldMineFieldWidth;
    private javax.swing.JTextField jTextFieldNumberOfMines;
    // End of variables declaration//GEN-END:variables
}
